# Scipio Circle-CI configuration file

version: 2

jobs:
  cargotest:
    docker:
      - image: cimg/base:2020.09
    steps:
      - run:
          name: Setup rust environment
          command: >- 
              curl -O https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init &&
              chmod +x rustup-init &&
	            ./rustup-init -y --default-toolchain 1.46.0 &&
	            rm rustup-init &&
	            rustc --version &&
	            cargo --version
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - run:
          name: OS info
          command: uname -a
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --all --all-targets -- --test-threads=1

  cargobuild:
    docker:
      - image: cimg/rust:1.46.0
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

  cargofmt:
    docker:
      - image: cimg/rust:1.46.0
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check formatting
          command: cargo fmt --all -- --check
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}

workflows:
  version: 2
  unit_tests:
    jobs:
      - cargofmt
      - cargobuild
      - cargotest
